name: Setup SOPS
author: nhedger
description: Setup SOPS in GitHub Actions
branding:
  color: gray-dark
  icon: lock
inputs:
  version:
    description: The version of SOPS to install
    required: true
    default: latest
  token:
    description: GitHub Actions token to authenticate API requests
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.mjs'
