name: Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        version: [ "latest", "3.7.3" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Exoscale CLI
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Test SOPS
        run: sops --version
